services:
  back:
    build:
      context: back
    container_name: back
    ports:
      - "3000:3000"
    env_file: ".env"
    networks:
      transcendence:
    restart: always
    init: true

  front:
    build:
      context: front
    container_name: front
    ports:
      - "5000:5000"
    depends_on:
      - back
    networks:
      transcendence:
    restart: always
    init: true

networks:
  transcendence:
    driver: bridge